stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/python:${CI_COMMIT_SHA}
  IMAGE_CACHE_NAME: $CI_REGISTRY_IMAGE/cache

build-buildkit:
  stage: build
  image:
    name: moby/buildkit:v0.15.2-rootless
    entrypoint: [ "sh", "-c" ]
  interruptible: true
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    DOCKER_CONFIG: /home/user/.docker
  before_script:
    - |
      mkdir $DOCKER_CONFIG
      cat <<EOF > "$DOCKER_CONFIG/config.json"
      {
          "auths": {
              "$CI_REGISTRY": {
                  "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64 )"
              }
          }
      }
      EOF
  script:
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --export-cache type=registry,ref="${IMAGE_CACHE_NAME}:${CI_COMMIT_REF_SLUG}",mode=max \
          --import-cache type=registry,ref="${IMAGE_CACHE_NAME}:${CI_DEFAULT_BRANCH}" \
          --import-cache type=registry,ref="${IMAGE_CACHE_NAME}:${CI_COMMIT_REF_SLUG}" \
          --output type=image,name=${IMAGE_NAME},push=true

